### ISSUE TITLE
Android Basics: lists

### ISSUE THREAD

**Issue by Gungy2** [google-developer-training/android-basics-kotlin-affirmations-app-solution#22] opened 2021-03-04 10:21 UTC
**URL of codelab**
[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-training-lists?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-lists#3)

**In which task and step of the codelab can this issue be found?**
Task 4 (Loop through a list)

**Describe the problem**
The division assignment operator used backslash instead of a slash ("\\=" instead of "/=")

**Additional information**
![Screenshot_20210304_121905](https://user-images.githubusercontent.com/64141526/109949259-d5200d00-7ce3-11eb-8e15-b82ecf24f4b5.png)

**Comment by osuleymanova** [comment] 2021-08-06 23:19
Duplicate of #38, #41 , #45

**Comment by osuleymanova** [comment] 2021-08-06 23:20
@Gungy2 
Thank you for reaching out to us. The issue is fixed and published.

https://developer.android.com/codelabs/basic-android-kotlin-training-lists?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-lists#3

**Closed by osuleymanova** 2021-08-06 23:20 UTC
