### ISSUE TITLE
Android Basics issue: Error performing 'scroll RecyclerView to: holder with view:

### ISSUE THREAD

**Issue by kyooryoo** [google-developer-training/android-basics-kotlin-affirmations-app-solution#114] opened 2022-03-12 00:23 UTC
**URL of codelab**
[7. Test the RecyclerView](https://developer.android.com/codelabs/android-basics-kotlin-affirmations-test-lists-and-adapters?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-affirmations-test-lists-and-adapters#6)

**In which task and step of the codelab can this issue be found?**
Start with a ViewInteraction, but this time pass in a new ViewMatcher (in this case, withText()).
This can be a number of things, but to serve the purposes of this test, use withText.

**Describe the problem**
Cannot scroll to holder view with specified test for the following error:
*androidx.test.espresso.PerformException: Error performing 'scroll RecyclerView to: holder with view: an instance of android.widget.TextView and view.getText() equals string from resource id: <2131689500>' on view 'view.getId() is <2131231058/com.example.affirmations:id/recycler_view>'.*

**Steps to reproduce?**
1. Go to: src/androidTest/java/com/example/affirmations/AffirmationsListTests.kt
2. Add following test code to function **scroll_to_item_by_id()**
```
    @Test
    fun scroll_to_item_by_text() {
        onView(withId(R.id.recycler_view)).perform(
            RecyclerViewActions
                .scrollTo<RecyclerView.ViewHolder>(
                    withText(R.string.affirmation10)
                )
        )

        onView(withText(R.string.affirmation10))
            .check(matches(isDisplayed()))
    }
```
5. See error:
<img width="1419" alt="截屏2022-03-12 上午8 21 29" src="https://user-images.githubusercontent.com/16432725/157995019-9927aa52-18a6-4376-a65f-1041722ea1df.png">

**Versions**
Android Studio Bumblebee | 2021.1.1 Patch 1
Build #AI-211.7628.21.2111.8139111, built on February 2, 2022

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by inusedname** [comment] 2022-04-30 03:54
Duplicate of [#107](https://github.com/google-developer-training/android-basics-kotlin-affirmations-app-solution/issues/107)

**Closed** 2024-01-11 21:29 UTC
