### ISSUE TITLE
Android Basics: recyclerview-scrollable-list

### ISSUE THREAD

**Issue by Jimnav-png** [google-developer-training/android-basics-kotlin-affirmations-app-solution#57] opened 2021-09-01 13:30 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-recyclerview-scrollable-list?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-recyclerview-scrollable-list#3

**In which task and step of the codelab can this issue be found?**
In the whole course.

**Describe the problem**
When the width has 768 pixels or less, the "Next" button is not reachable.

**Additional information**
![image](https://user-images.githubusercontent.com/69730072/131679661-c5be4680-2e66-4844-a84b-f20225e01f99.png)
![image](https://user-images.githubusercontent.com/69730072/131680127-1f54b1ce-3356-4948-a5e5-b74d305aadf2.png)

**Comment by osuleymanova** [comment] 2022-06-02 19:34
@Jimnav-png 
Thank you for reaching out to us. The issue is closed as not reproducible:
![Screen Shot 2022-06-02 at 12 31 56 PM](https://user-images.githubusercontent.com/86437155/171723627-c96b791c-08ab-4ec8-aec0-3eceba554656.png)
:

**Closed by osuleymanova** 2022-06-02 19:34 UTC
